spring:
  application:
    name: goods-price-tracker
  config:
    import: optional:configserver:http://localhost:8888
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop_price_tracker_db
    username: postgres
    password: biba0218
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


